logging:
  level:
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true



#  datasource:
#    url: jdbc:h2:mem:online_store_db
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password